project_id = "vkeliqjedbqqhitehoys"

[functions.ingest-news]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.tg-login-start]
verify_jwt = false

[functions.tg-login-poll]
verify_jwt = false

[functions.tg-login-bot-poll]
verify_jwt = false
