TICKERS = [
    {"ticker": "AFKS", "name": "АФК Система", "aliases": ["АФК Система", "AFKS", "Система"]},
    {"ticker": "AFLT", "name": "Аэрофлот", "aliases": ["Аэрофлот", "AFLT", "Aeroflot"]},
    {"ticker": "ALRS", "name": "АЛРОСА", "aliases": ["АЛРОСА", "ALRS", "Alrosa"]},
    {"ticker": "BSPB", "name": "Банк СПБ", "aliases": ["Банк СПБ", "BSPB", "Банк Санкт-Петербург"]},
    {"ticker": "CBOM", "name": "Совкомбанк", "aliases": ["Совкомбанк", "CBOM", "Sovcombank"]},
    {"ticker": "CHMF", "name": "Северсталь", "aliases": ["Северсталь", "CHMF", "Severstal"]},
    {"ticker": "ENPG", "name": "Энел Россия", "aliases": ["Энел Россия", "ENPG", "Enel Russia"]},
    {"ticker": "FLOT", "name": "Совкомфлот", "aliases": ["Совкомфлот", "FLOT", "Sovcomflot"]},
    {"ticker": "GAZP", "name": "Газпром", "aliases": ["Газпром", "GAZP", "Gazprom"]},
    {"ticker": "GMKN", "name": "Норникель", "aliases": ["Норникель", "GMKN", "Norilsk Nickel", "Норильский никель"]},
    {"ticker": "HEAD", "name": "HeadHunter", "aliases": ["HeadHunter", "HEAD", "Хедхантер"]},
    {"ticker": "IRAO", "name": "Интер РАО", "aliases": ["Интер РАО", "IRAO", "Inter RAO"]},
    {"ticker": "LKOH", "name": "Лукойл", "aliases": ["Лукойл", "LKOH", "Lukoil"]},
    {"ticker": "MAGN", "name": "ММК", "aliases": ["ММК", "MAGN", "Магнитогорский металлургический комбинат", "Магнитка"]},
    {"ticker": "MDMG", "name": "Мечел", "aliases": ["Мечел", "MDMG", "Mechel"]},
    {"ticker": "MOEX", "name": "Мосбиржа", "aliases": ["Мосбиржа", "MOEX", "Московская биржа", "MOEX Russia"]},
    {"ticker": "MSNG", "name": "Мосэнерго", "aliases": ["Мосэнерго", "MSNG", "Mosenergo"]},
    {"ticker": "MTSS", "name": "МТС", "aliases": ["МТС", "MTSS", "MTS"]},
    {"ticker": "NLMK", "name": "НЛМК", "aliases": ["НЛМК", "NLMK", "Novolipetsk Steel"]},
    {"ticker": "NVTK", "name": "Новатэк", "aliases": ["Новатэк", "NVTK", "Novatek"]},
    {"ticker": "PHOR", "name": "ФосАгро", "aliases": ["ФосАгро", "PHOR", "PhosAgro"]},
    {"ticker": "PIKK", "name": "ПИК", "aliases": ["ПИК", "PIKK", "PIK Group"]},
    {"ticker": "PLZL", "name": "Полюс", "aliases": ["Полюс", "PLZL", "Polyus", "Полюс Золото"]},
    {"ticker": "POSI", "name": "Positive Technologies", "aliases": ["Positive Technologies", "POSI", "Позитив"]},
    {"ticker": "RENI", "name": "Ренессанс Страхование", "aliases": ["Ренессанс Страхование", "RENI", "Renaissance Insurance"]},
    {"ticker": "ROSN", "name": "Роснефть", "aliases": ["Роснефть", "ROSN", "Rosneft"]},
    {"ticker": "RTKM", "name": "Ростелеком", "aliases": ["Ростелеком", "RTKM", "Rostelecom"]},
    {"ticker": "RUAL", "name": "Русал", "aliases": ["Русал", "RUAL", "Rusal"]},
    {"ticker": "SBER", "name": "Сбербанк", "aliases": ["Сбербанк", "SBER", "Сбер", "Sberbank"]},
    {"ticker": "SBERP", "name": "Сбербанк преф", "aliases": ["Сбербанк преф", "SBERP", "Сбер преф"]},
    {"ticker": "SNGS", "name": "Сургутнефтегаз", "aliases": ["Сургутнефтегаз", "SNGS", "Surgutneftegaz"]},
    {"ticker": "SNGSp", "name": "Сургутнефтегаз преф", "aliases": ["Сургутнефтегаз преф", "SNGSp", "Сург преф"]},
    {"ticker": "SVCB", "name": "Совкомбанк", "aliases": ["Совкомбанк", "SVCB"]},
    {"ticker": "T", "name": "Т-Технологии", "aliases": ["Т-Технологии", "Т-Банк", "Тинькофф", "TCS", "Т", "Tinkoff", "Т-Тех"]},
    {"ticker": "TATN", "name": "Татнефть", "aliases": ["Татнефть", "TATN", "Tatneft"]},
    {"ticker": "TATNp", "name": "Татнефть преф", "aliases": ["Татнефть преф", "TATNp", "Татнефть-п"]},
    {"ticker": "TRNFp", "name": "Транснефть преф", "aliases": ["Транснефть преф", "TRNFp", "Транснефть"]},
    {"ticker": "UGLD", "name": "Полюс Золото", "aliases": ["Полюс Золото", "UGLD"]},
    {"ticker": "UPRO", "name": "Юнипро", "aliases": ["Юнипро", "UPRO", "Unipro"]},
    {"ticker": "VKCO", "name": "VK", "aliases": ["VK", "VKCO", "ВКонтакте", "Mail.ru", "ВК"]},
    {"ticker": "VTBR", "name": "ВТБ", "aliases": ["ВТБ", "VTBR", "VTB"]},
    {"ticker": "X5", "name": "X5 Group", "aliases": ["X5 Group", "X5", "Пятёрочка", "Перекрёсток"]},
    {"ticker": "YDEX", "name": "Яндекс", "aliases": ["Яндекс", "YDEX", "Yandex"]},
]
